update deps for core v2.2.1
classic-terra/mantlemint pull request #4
Opened 2023-09-05 03:05 UTC by nghuyenthevinh2000

2023-09-08 10:17 UTC, inon-man requested changes
some module must be replaced. i.e. goleveldb
I will update it.

2023-09-10 14:40 UTC, inon-man approved these changes

2023-09-10 15:42 UTC, nghuyenthevinh2000 commented
I assumed that you have tested this one against rebel-2 and therefore approved?

2023-09-10 17:38 UTC, inon-man commented
> I assumed that you have tested this one against rebel-2 and therefore approved?

Oh I actually did it on my local network. I don't know where the genesis, seed, and peer of rebel-2 is located at. Is there available RPC node in public?

Nevermind, I found it. https://github.com/classic-terra/documents/blob/main/guides/rebel-2-upgrade-guide.md

2023-09-12 10:40 UTC, merged